from fw_test.cloud import PacketType

STATE_MANUAL = {
    "clientToken": 0,
    "timestamp": 0,
    "requestId": 0,
    "type": PacketType.STATE_DESIRED_V2,
    "systemConfiguration": 0,
    "metricInterval": 20,
    "powerConfig": 100,
    "openWindowOffTimeMinutes": 15,
    "setPointOff": 50,
    "setPointEco": 80,
    "manualSetPoint": 120,
    "temporaryManualSetPoint": 0,
    "boostDuration": 100,
    "hysteresis": 5,
    "temperatureSensorOffset": 0,
    "ledStatus": 0,
    "envId": [],
    "temporaryManualEnd": 0,
    "holidayStart": 0,
    "holidayEnd": 0,
    "timezone": 60,
    "schedule": [0] * 154,
    "ledEnable": 0,
    "ledMode": 0,
    "ledSchedule": [0] * 154,
    "ledColors": [0] * 10 * 4,
    "temporaryManualLedSetPoint": 0,
    "estimatedTemperature": 0,
    "externalTemperature": 0,
    "estimatedHumidity": 0,
    "externalHumidity": 0,
    "timesyncServer": [0] * 32,
    "forFutureUsage": [0] * 68,
}